name: sentiment_analyzer
description: Un paquete de Flutter para el analisis de sentimientos mediante deteccion de malla facial.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_commons: ^0.11.0
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.0
  camera: ^0.11.0
  provider: ^6.1.1
  vibration: ^3.1.0
  url_launcher: ^6.2.0
  video_player: ^2.8.1
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/emotion_model.tflite